package managment.actionManagement.actions;

public enum ActionType {
    BEFORE_DEAL_DAMAGE, AFTER_DEAL_DAMAGE
    , ATTACK, TREATMENT, BEFORE_USED_SKILL, AFTER_USED_SKILL
    , START_TURN, END_TURN, SKIP_TURN
    , SWAP_HEROES, AFTER_USED_BONUS, BEFORE_USED_BONUS
    , PLAYER_OUT, END_GAME, GET_FRAME
}
