package managment.actionManagement.actions;

public enum ActionType {
    BEFORE_DEAL_DAMAGE, AFTER_DEAL_DAMAGE
    , BEFORE_ATTACK, AFTER_ATTACK
    , BEFORE_TREATMENT, AFTER_TREATMENT
    , BEFORE_USED_SKILL, AFTER_USED_SKILL
    , START_TURN, END_TURN, SKIP_TURN, SWAP_HEROES
    , AFTER_USED_BONUS, BEFORE_USED_BONUS, SHOWED_BONUSES
    , PLAYER_OUT, END_GAME, GET_FRAME
}
